apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      containers:
        - name: ping-pong
          image: jan5u/ping-pong:latest
          env:
            - name: PGDATABASE
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_DB
            - name: PGUSER
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_USER
            - name: PGPASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: POSTGRES_PASSWORD
            - name: PGHOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: PGHOST
            - name: PGPORT
              valueFrom:
                configMapKeyRef:
                  name: postgres-configuration
                  key: PGPORT
