apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configuration
  namespace: exercises
  labels:
    app: postgres
data:
  POSTGRES_DB: awesomedb
  POSTGRES_USER: amazinguser
  POSTGRES_PASSWORD: cGVyZmVjdHBhc3N3b3Jk
  PGHOST: postgres-svc
  PGPORT: "5432"
