apiVersion: batch/v1
kind: CronJob
metadata:
  name: daily-todos
  namespace: exercises
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: daily-todos
              image: jan5u/daily-todos:latest
              imagePullPolicy: IfNotPresent
          restartPolicy: OnFailure
