apiVersion: apps/v1
kind: Deployment
metadata:
  name: randomstring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
        - name: random-string
          image: jan5u/random-string:latest
